// src/app/components/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { CardModule } from 'primeng/card';
import { ButtonModule } from 'primeng/button';
import { ProgressBarModule } from 'primeng/progressbar';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule, CardModule, ButtonModule, ProgressBarModule],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
  // Statistiques principales
  statistics = [
    { label: 'Projets générés', value: '12', icon: 'folder', color: '#f59e0b' },
    { label: 'Modules complétés', value: '8/15', icon: 'book', color: '#3b82f6' },
    { label: 'Score moyen PMP', value: '78%', icon: 'chart-line', color: '#10b981' },
    { label: 'Temps d\'étude', value: '24h', icon: 'clock', color: '#ef4444' }
  ];

  // Données de progression
  progressData = [
    { label: 'Formation PMP', value: 53, color: '#f59e0b' },
    { label: 'Simulateur d\'examen', value: 78, color: '#f59e0b' },
    { label: 'Projets générés', value: 100, color: '#f59e0b' }
  ];

  // Activité récente
  recentActivity = [
    { title: 'Module "Gestion des risques" complété', time: 'Il y a 2 heures', icon: 'check-circle', color: '#10b981' },
    { title: 'Projet "Application mobile" généré', time: 'Hier', icon: 'folder-plus', color: '#f59e0b' },
    { title: 'Test PMP réalisé - Score: 82%', time: 'Il y a 2 jours', icon: 'calculator', color: '#3b82f6' },
    { title: 'Certificat de formation téléchargé', time: 'Il y a 3 jours', icon: 'download', color: '#8b5cf6' }
  ];

  // Actions rapides
  quickActions = [
    { title: 'Nouveau projet', description: 'Créer un nouveau projet', icon: 'plus', color: '#f59e0b', action: 'new-project' },
    { title: 'Continuer la formation', description: 'Reprendre où vous vous êtes arrêté', icon: 'play', color: '#3b82f6', action: 'continue-training' },
    { title: 'Test PMP', description: 'Évaluer vos connaissances', icon: 'calculator', color: '#10b981', action: 'pmp-test' }
  ];

  // Navigation sidebar
  sidebarItems = [
    { icon: 'home', label: 'Tableau de bord', active: true, route: '/dashboard' },
    { icon: 'folder', label: 'Générateur de projets', active: false, route: '/project-generator' },
    { icon: 'book', label: 'Formation PMP', active: false, route: '/training' },
    { icon: 'calculator', label: 'Simulateur PMP', active: false, route: '/simulator' },
    { icon: 'chart-line', label: 'Progression', active: false, route: '/history' },
    { icon: 'cog', label: 'Paramètres', active: false }
  ];

  constructor(private router: Router) {}

  onGenerateProject() {
    this.router.navigate(['/project-generator']);
  }

  onAccessSimulator() {
    this.router.navigate(['/simulator']);
  }

  onQuickAction(action: string) {
    switch(action) {
      case 'new-project':
        this.router.navigate(['/project-generator']);
        break;
      case 'continue-training':
        this.router.navigate(['/training']);
        break;
      case 'pmp-test':
        this.router.navigate(['/simulator']);
        break;
    }
  }

  onLogout() {
    this.router.navigate(['/']);
  }

  onSidebarItemClick(item: any) {
    // Désactiver tous les items
    this.sidebarItems.forEach(i => i.active = false);
    // Activer l'item cliqué
    item.active = true;
    
    if (item.route) {
      this.router.navigate([item.route]);
    }
  }
}
<!-- Main Layout avec PrimeNG -->
<div class="min-h-screen bg-gray-50 flex">
  <!-- Sidebar -->
  <div class="w-64 bg-white shadow-sm border-r border-gray-200 flex flex-col">
    <!-- Logo -->
    <div class="p-6 border-b border-gray-200">
      <div class="flex items-center space-x-3">
        <div class="w-10 h-10 bg-orange-500 rounded-lg flex items-center justify-center">
          <span class="text-white font-bold text-sm">SC</span>
        </div>
        <span class="font-semibold text-gray-900">SICA CONSEIL</span>
      </div>
    </div>

    <!-- Navigation avec PrimeNG -->
    <nav class="flex-1 p-4">
      <ul class="space-y-2">
        <li *ngFor="let item of sidebarItems">
          <button
            pButton
            [label]="item.label"
            [icon]="'pi pi-' + item.icon"
            (click)="onSidebarItemClick(item)"
            class="w-full justify-start text-left"
            [class]="item.active ? 'p-button-warning p-button-outlined' : 'p-button-text'"
            [severity]="item.active ? 'warning' : 'secondary'">
          </button>
        </li>
      </ul>
    </nav>

    <!-- Déconnexion -->
    <div class="p-4 border-t border-gray-200">
      <p-button
        label="Déconnexion"
        icon="pi pi-sign-out"
        severity="danger"
        [text]="true"
        class="w-full"
        (onClick)="onLogout()">
      </p-button>
    </div>
  </div>

  <!-- Main Content -->
  <div class="flex-1 p-8">
    <!-- Header -->
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-900 mb-2">Bienvenue sur SICA CONSEIL !</h1>
      <p class="text-gray-600">Votre plateforme complète pour la gestion de projet et la certification PMP</p>
    </div>

    <!-- Hero Banner avec PrimeNG Card -->
    <p-card class="mb-8 bg-gradient-to-r from-orange-400 to-orange-600 text-white">
      <div class="text-center py-8">
        <h2 class="text-2xl font-bold mb-4 text-white">Bienvenue sur SICA CONSEIL !</h2>
        <p class="text-orange-100 mb-6">Votre plateforme complète pour la gestion de projet et la certification PMP</p>
        
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <p-button
            label="Générer un projet"
            icon="pi pi-folder-plus"
            severity="secondary"
            (onClick)="onGenerateProject()">
          </p-button>
          <p-button
            label="Simulateur PMP"
            icon="pi pi-calculator"
            [outlined]="true"
            severity="secondary"
            (onClick)="onAccessSimulator()">
          </p-button>
        </div>
      </div>
    </p-card>

    <!-- Statistics Cards avec Bootstrap Grid -->
    <div class="row g-4 mb-8">
      <div class="col-md-3" *ngFor="let stat of statistics">
        <p-card class="h-100 text-center">
          <div class="mb-3">
            <i [class]="'pi pi-' + stat.icon + ' text-3xl'" [style.color]="stat.color"></i>
          </div>
          <h3 class="text-2xl font-bold text-gray-900 mb-1">{{ stat.value }}</h3>
          <p class="text-sm text-gray-600 mb-0">{{ stat.label }}</p>
        </p-card>
      </div>
    </div>

    <!-- Content Grid avec Bootstrap -->
    <div class="row g-6">
      <!-- Progression -->
      <div class="col-lg-6">
        <p-card>
          <ng-template pTemplate="header">
            <div class="p-4 border-bottom">
              <h3 class="text-xl font-semibold text-gray-900 mb-1">
                <i class="pi pi-chart-line mr-2"></i>
                Votre progression
              </h3>
              <p class="text-gray-600 text-sm mb-0">Suivez vos progrès dans la formation PMP</p>
            </div>
          </ng-template>
          
          <div class="space-y-4">
            <div *ngFor="let progress of progressData">
              <div class="flex justify-between items-center mb-2">
                <span class="text-sm font-medium text-gray-700">{{ progress.label }}</span>
                <span class="text-sm font-semibold text-gray-900">{{ progress.value }}%</span>
              </div>
              <p-progressBar 
                [value]="progress.value" 
                [style]="{'height': '8px'}"
                [color]="progress.color">
              </p-progressBar>
            </div>
          </div>
          
          <ng-template pTemplate="footer">
            <p-button
              label="Voir les détails"
              [text]="true"
              severity="secondary"
              class="w-full">
            </p-button>
          </ng-template>
        </p-card>
      </div>

      <!-- Activité récente -->
      <div class="col-lg-6">
        <p-card>
          <ng-template pTemplate="header">
            <div class="p-4 border-bottom">
              <h3 class="text-xl font-semibold text-gray-900 mb-1">
                <i class="pi pi-clock mr-2"></i>
                Activité récente
              </h3>
              <p class="text-gray-600 text-sm mb-0">Vos dernières actions sur la plateforme</p>
            </div>
          </ng-template>
          
          <div class="space-y-4">
            <div *ngFor="let activity of recentActivity" class="flex items-start space-x-3">
              <div class="w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0"
                   [style.background-color]="activity.color + '20'">
                <i [class]="'pi pi-' + activity.icon + ' text-sm'" [style.color]="activity.color"></i>
              </div>
              <div class="flex-1 min-w-0">
                <p class="text-sm font-medium text-gray-900">{{ activity.title }}</p>
                <p class="text-xs text-gray-500">{{ activity.time }}</p>
              </div>
            </div>
          </div>
        </p-card>
      </div>
    </div>

    <!-- Actions rapides -->
    <p-card class="mt-8">
      <ng-template pTemplate="header">
        <div class="p-4 border-bottom">
          <h3 class="text-xl font-semibold text-gray-900 mb-1">Actions rapides</h3>
          <p class="text-gray-600 text-sm mb-0">Accédez rapidement aux fonctionnalités principales</p>
        </div>
      </ng-template>
      
      <div class="row g-4">
        <div class="col-md-4" *ngFor="let action of quickActions">
          <div class="text-center p-4 border border-gray-200 rounded-lg hover:shadow-md transition-shadow cursor-pointer"
               (click)="onQuickAction(action.action)">
            <div class="w-16 h-16 mx-auto mb-3 rounded-full flex items-center justify-center"
                 [style.background-color]="action.color + '20'">
              <i [class]="'pi pi-' + action.icon + ' text-2xl'" [style.color]="action.color"></i>
            </div>
            <h4 class="font-semibold text-gray-900 mb-2">{{ action.title }}</h4>
            <p class="text-sm text-gray-600">{{ action.description }}</p>
          </div>
        </div>
      </div>
    </p-card>
  </div>
</div>

// app/dashboard/page.tsx
"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { FileText, BookOpen, Award, TrendingUp, Clock, CheckCircle, BarChart3, Download, Play } from "lucide-react"
import Link from "next/link"
import DashboardLayout from "@/components/dashboard-layout"

export default function DashboardPage() {
  return (
    <DashboardLayout>
      <div className="space-y-8">
        {/* Welcome Section */}
        <div className="bg-gradient-to-r from-amber-600 via-yellow-600 to-amber-600 rounded-lg p-6 text-white shadow-2xl">
          <h1 className="text-3xl font-bold mb-2">Bienvenue sur SICA CONSEIL !</h1>
          <p className="text-blue-100 mb-4">
            Votre plateforme complète pour la gestion de projet et la certification PMP
          </p>
          <div className="flex flex-wrap gap-4">
            <Link href="/dashboard/project-generator">
              <Button className="bg-white text-amber-600 hover:bg-amber-50 shadow-lg">
                <FileText className="w-4 h-4 mr-2" />
                Générer un projet
              </Button>
            </Link>
            <Link href="/dashboard/pmp-simulator">
              <Button
                variant="outline"
                className="border-white text-white hover:bg-white hover:text-amber-600 bg-transparent shadow-lg"
              >
                <Award className="w-4 h-4 mr-2" />
                Simulateur PMP
              </Button>
            </Link>
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Projets générés</p>
                  <p className="text-2xl font-bold">12</p>
                </div>
                <FileText className="w-8 h-8 text-amber-600" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Modules complétés</p>
                  <p className="text-2xl font-bold">8/15</p>
                </div>
                <BookOpen className="w-8 h-8 text-amber-500" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Score moyen PMP</p>
                  <p className="text-2xl font-bold">78%</p>
                </div>
                <TrendingUp className="w-8 h-8 text-yellow-600" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600">Temps d'étude</p>
                  <p className="text-2xl font-bold">24h</p>
                </div>
                <Clock className="w-8 h-8 text-orange-600" />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Main Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Progress Section */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="w-5 h-5" />
                Votre progression
              </CardTitle>
              <CardDescription>Suivez vos progrès dans la formation PMP</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <div className="flex justify-between items-center mb-2">
                  <span className="text-sm font-medium">Formation PMP</span>
                  <span className="text-sm text-gray-500">53%</span>
                </div>
                <Progress value={53} className="h-2" />
              </div>

              <div>
                <div className="flex justify-between items-center mb-2">
                  <span className="text-sm font-medium">Simulateur d'examen</span>
                  <span className="text-sm text-gray-500">78%</span>
                </div>
                <Progress value={78} className="h-2" />
              </div>

              <div>
                <div className="flex justify-between items-center mb-2">
                  <span className="text-sm font-medium">Projets générés</span>
                  <span className="text-sm text-gray-500">100%</span>
                </div>
                <Progress value={100} className="h-2" />
              </div>

              <Link href="/dashboard/progress">
                <Button variant="outline" className="w-full bg-transparent">
                  Voir les détails
                </Button>
              </Link>
            </CardContent>
          </Card>

          {/* Recent Activity */}
          <Card>
            <CardHeader>
              <CardTitle>Activité récente</CardTitle>
              <CardDescription>Vos dernières actions sur la plateforme</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-gradient-to-br from-amber-100 to-yellow-100 rounded-full flex items-center justify-center">
                    <CheckCircle className="w-4 h-4 text-amber-600" />
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-medium">Module "Gestion des risques" complété</p>
                    <p className="text-xs text-gray-500">Il y a 2 heures</p>
                  </div>
                </div>

                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-gradient-to-br from-amber-100 to-yellow-100 rounded-full flex items-center justify-center">
                    <FileText className="w-4 h-4 text-amber-600" />
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-medium">Projet "Application mobile" généré</p>
                    <p className="text-xs text-gray-500">Hier</p>
                  </div>
                </div>

                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-gradient-to-br from-amber-100 to-yellow-100 rounded-full flex items-center justify-center">
                    <Award className="w-4 h-4 text-amber-600" />
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-medium">Test PMP réalisé - Score: 82%</p>
                    <p className="text-xs text-gray-500">Il y a 2 jours</p>
                  </div>
                </div>

                <div className="flex items-center space-x-3">
                  <div className="w-8 h-8 bg-gradient-to-br from-amber-100 to-yellow-100 rounded-full flex items-center justify-center">
                    <Download className="w-4 h-4 text-amber-600" />
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-medium">Certificat de formation téléchargé</p>
                    <p className="text-xs text-gray-500">Il y a 3 jours</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Quick Actions */}
        <Card>
          <CardHeader>
            <CardTitle>Actions rapides</CardTitle>
            <CardDescription>Accédez rapidement aux fonctionnalités principales</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <Link href="/dashboard/project-generator">
                <Button
                  variant="outline"
                  className="w-full h-20 flex flex-col items-center justify-center space-y-2 bg-transparent"
                >
                  <FileText className="w-6 h-6" />
                  <span>Nouveau projet</span>
                </Button>
              </Link>

              <Link href="/dashboard/pmp-training">
                <Button
                  variant="outline"
                  className="w-full h-20 flex flex-col items-center justify-center space-y-2 bg-transparent"
                >
                  <Play className="w-6 h-6" />
                  <span>Continuer la formation</span>
                </Button>
              </Link>

              <Link href="/dashboard/pmp-simulator">
                <Button
                  variant="outline"
                  className="w-full h-20 flex flex-col items-center justify-center space-y-2 bg-transparent"
                >
                  <Award className="w-6 h-6" />
                  <span>Test PMP</span>
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  )
}
